### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by CheneyL-nankai** [YuboZhangPKU/ERICA#10]
老师好，通过学习这个软件让我受益匪浅。但是我在运行第二步的时候出现了这种问题，目前没有找到解决办法，希望可以得到老师的解答！非常感谢！
2024-07-18 10:22:56.181850: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-07-18 10:22:56.181884: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/dell/miniconda3/envs/ERICA/lib/python3.6/site-packages/keras/legacy_tf_layers/core.py:236: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  warnings.warn('`tf.layers.dense` is deprecated and '
/home/dell/miniconda3/envs/ERICA/lib/python3.6/site-packages/keras/engine/base_layer_v1.py:1676: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
------------------------------
2024-07-18 10:23:03.279934: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-07-18 10:23:03.280035: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2024-07-18 10:23:03.280084: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2024-07-18 10:23:03.280129: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2024-07-18 10:23:03.280174: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2024-07-18 10:23:03.280215: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2024-07-18 10:23:03.280257: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2024-07-18 10:23:03.280302: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2024-07-18 10:23:03.280319: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-07-18 10:23:03.281195: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Thu Jul 18 10:23:03 2024	test3/pop_test_Chr01.txt	Data Preprocessing > > > > > > > > > > 
Process Process-1:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/ERICA/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/dell/miniconda3/envs/ERICA/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "ERICAPrediction.py", line 112, in FourTaxonDataPrediction
    data = FourTaxonDataProcess(MSA)
  File "ERICAPrediction.py", line 71, in FourTaxonDataProcess
    lines = np.array([list(x) for x in lines], dtype=np.uint8)
ValueError: setting an array element with a sequence.
我的数据使用的是使用vcf和参考fasta文件获得的MSA文件，使用的四组分，每个组分含有四个双倍体个体序列

**Comment by YuboZhangPKU** [comment]
您好，感谢您的使用。该报错可能是由于输入数据格式存在问题造成的。模型输入为多序列比对结果，目前仅支持ATCGN-及对应小写字符。请您再检查一下输入文件中是否存在其他字符。如果存在，可能是由于vcf文件格式上的差异，基因型信息中存在其他字符，可能需要在转换之前或之后将其去除。

**Comment by CheneyL-nankai** [comment]
![a25dbe731e7d4f92b1e5a76a29fb465](https://github.com/user-attachments/assets/738bd0be-9f5d-4137-bf2a-3696ffe21b43)
感谢您的解答！我得到的MSA文件中一部分如图所示，这种格式看起来就是您说的ATCGN字符，目前没有发现其他字符。不知道您还有没有其他的意见或者建议呢？

**Comment by YuboZhangPKU** [comment]
您好，您可以考虑统计一下输入文件内所有存在的字符？例如可以利用awk 命令 awk '{for(i=1;i<=length($0);i++) ++S[substr($0,i,1)]} END {for (a in S) print(S[a],a)}' input_file 或使用其他文本处理的命令进行统计。

**Comment by CheneyL-nankai** [comment]
您好！我已经解决了我的问题，问题是因为我的VCF文件处理时没有将小片段的插入或缺失序列删除导致MSA文件没有对齐，目前已经解决，非常感谢您的解答！
