### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by pengyan19** [YuboZhangPKU/ERICA#2]
你好：我想问一下：P1,P2,P3,Outgroup 的搭配能用这个软件吗？还有每个群体只能用四个个体吗？

**Comment by YuboZhangPKU** [comment]
您好，软件提供了4类群和5类群的网络模型，其中4类群模型适用于分析P1, P2, P3, Outgroup的演化情境。当前模型的输入格式为每个类群8条序列，更少的个体可以考虑随机重复取样，而更多的个体可能可以考虑随机采样。

**Comment by pengyan19** [comment]
您好；我用测试数据尝试运行，但是报错是这样，请问是软件没有安装成功吗？

Four populations will be analysed.
pop1	H_m_aglaope_1
pop1	H_m_aglaope_2
pop1	H_m_aglaope_3
pop1	H_m_aglaope_4
pop2	H_m_amaryllis_1
pop2	H_m_amaryllis_2
pop2	H_m_amaryllis_3
pop2	H_m_amaryllis_4
pop3	H_t_thelxinoe_1
pop3	H_t_thelxinoe_2
pop3	H_t_thelxinoe_3
pop3	H_t_thelxinoe_4
pop4	H_ethilla_1
pop4	H_ethilla_2
pop4	H_ethilla_3
pop4	H_ethilla_4
Tue Jun 27 15:24:21 2023	Chromosome Hmel218003o will be analysed.
Tue Jun 27 15:24:26 2023	Chromosome Hmel218003o done.
WARNING:tensorflow:From /public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From ERICAPrediction.py:214: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From /public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
------------------------------
2023-06-27 15:25:56.786513: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2023-06-27 15:25:58.389149: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2023-06-27 15:25:58.454200: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5629c42e4ab0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-06-27 15:25:58.455502: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-06-27 15:25:58.538647: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Tue Jun 27 15:26:00 2023	test/pop_test_Hmel218003o.txt	Data Preprocessing > > > > > > > > > > 

Shape of MSA: (32, 1000000)
Shape of datas: (200, 128, 5000)
Tue Jun 27 15:26:05 2023	test/pop_test_Hmel218003o.txt	Data Preprocessing done > > > > > > > > > > 

Tue Jun 27 15:26:05 2023	Predictions will be writen into test/pop_test_Hmel218003o_res.txt.
Traceback (most recent call last):
  File "ERICAVisualization.py", line 115, in <module>
    mean_data_df.columns = TopoName
  File "/public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/pandas/core/generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/pandas/core/generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "/public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 178, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
Five populations will be analysed.
pop1	GP39
pop1	GP77
pop1	GP536
pop1	GP640
pop1	GP761-1
pop1	GP77
pop1	GP77
pop1	GP536
pop2	Nipponbare
pop2	HP14
pop2	HP44
pop2	HP48
pop2	HP314
pop2	HP103
pop2	HP45
pop2	UR28
pop3	W1943
pop3	W3095-2
pop3	Orufi
pop3	W3078-2
pop3	W1943
pop3	W3095-2
pop3	Orufi
pop3	W3078-2
pop4	W0170
pop4	W1698
pop4	W1754
pop4	W0123-1
pop4	Oniva
pop4	W0123-1
pop4	W1754
pop4	W1754
pop5	Obart
pop5	Obart
pop5	Obart
pop5	Obart
pop5	Obart
pop5	Obart
pop5	Obart
pop5	Obart
Tue Jun 27 15:27:56 2023	Chromosome 10 will be analysed.
Tue Jun 27 15:28:01 2023	Chromosome 10 done.
WARNING:tensorflow:From /public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From ERICAPrediction.py:291: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From /public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
------------------------------
2023-06-27 15:29:04.857369: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2023-06-27 15:29:05.096668: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2023-06-27 15:29:05.102854: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55cc51fd4870 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-06-27 15:29:05.103016: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-06-27 15:29:05.104336: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Tue Jun 27 15:29:06 2023	test/five_pop_test_10.txt	Data Preprocessing > > > > > > > > > > 

Traceback (most recent call last):
  File "ERICAVisualization.py", line 115, in <module>
    mean_data_df.columns = TopoName
  File "/public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/pandas/core/generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/pandas/core/generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "/public/home/pengyan/anaconda3/envs/ERICA2/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 178, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements

**Comment by YuboZhangPKU** [comment]
您好，我们在目前的log文件中没有看到软件安装方面的报错。由于测试脚本中包括多个命令，目前无法确认是哪一步骤出现了问题。您可以再查看一下每一步骤的输出文件是否正常。

**Comment by pengyan19** [comment]
非常感谢，很漂亮的工作，我的已经运行正常。ILS会有影响渐渗区域的结果，请问您们这个方法在不模拟真实的种群历史的模型的话，直接用你们的训练好的模型，来检测渐渗区域，会不会能很好的避免ILS的影响吗？

**Comment by YuboZhangPKU** [comment]
您好，ILS确实会影响渗入检测的效果，特别是在种群历史未知的情况下，可能较难确定一个阈值区分ILS和渗入。因此我们评估了在ILS最强烈的情况下其如何影响拓扑结构，并评估了以此作为阈值检测渗入信号的效果。结果显示对于适应性渗入仍能获得较高的准确性，但对于一些低强度的中性渗入，可能会存在无法检测到的问题。
