### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tcd11221** [YuboZhangPKU/ERICA#3]
python "/home/share_data1/tiancd/00.software/ERICA/vcf2MSA.py" -i new.test.vcf -r 1316.genome.fasta -o pop_test -f diplo -P1 pop1-108,pop1-xyy,pop1-bl,pop1-mgy -P2 pop2-107,pop2-17,pop2-203,pop2-214 -P3 pop3-69,pop3-1041,pop3-351,pop3-352 -P4 pop4-101,pop4-hy,pop4-xjy,pop4-1316
Four populations will be analysed.
pop1    pop1-108
pop1    pop1-xyy
pop1    pop1-bl
pop1    pop1-mgy
pop2    pop2-107
pop2    pop2-17
pop2    pop2-203
pop2    pop2-214
pop3    pop3-69
pop3    pop3-1041
pop3    pop3-351
pop3    pop3-352
pop4    pop4-101
pop4    pop4-hy
pop4    pop4-xjy
pop4    pop4-1316
Thu Jun 29 23:12:55 2023        Chromosome Chr01 will be analysed.
Traceback (most recent call last):
  File "/home/share_data1/tiancd/00.software/ERICA/vcf2MSA.py", line 212, in <module>
    if GT[j] == '.':
IndexError: list index out of range

Hi, I have encountered the following error when using the software and have been unable to resolve it, what could be the cause?

**Comment by YuboZhangPKU** [comment]
Hello, the script vcf2MSA.py converts the genotype information (GT field) in the vcf file to a msa. When the 'diplo' parameter is used, the two genotypes in GT (separated by  '/' or '|’) will be used. Please check if all the individuals used have the two copies of the alleles.

**Comment by echolihuifang** [comment]
Wed Oct  4 23:43:00 2023	Chromosome Chr1 will be analysed.
Traceback (most recent call last):
  File "vcf2MSA.py", line 202, in <module>
    if GT[j] == '.':
IndexError: list index out of range

张老师您好，我在使用ERICA第一步vcf转MSA时遇到如上报错，解决不了，想请教您该如何解决？谢谢。

**Comment by hfLi66** [comment]
> python “/home/share_data1/tiancd/00.software/ERICA/vcf2MSA.py” -i new.test.vcf -r 1316.genome.fasta -o pop_test -f diplo -P1 pop1-108，pop1-xyy，pop1-bl，pop1-mgy -P2 pop2-107，pop2-17，pop2-203，pop2-214 -P3 pop3-69，pop3-1041，pop3-351，pop3-352 -P4 pop4-101，pop4-hy，pop4-xjy，pop4-1316 将分析四个人群。流行1 流行1-108 流行1 流行1-xyy 流行1 流行1-BL 流行1 流行1-MGY 流行2 流行2-107 流行2 流行2-17 流行2 流行2-203 流行2 流行2-214 流行3 流行3-69 流行3 流行3-1041 流行3 流行3-351 流行3-3 流行352 流行4-4 流行101 流行4-hy 流行4 流行4-xjy 流行4 流行4-4 周四 1316 月 29 日 23：12：55 2023 将分析染色体 Chr01。回溯（最近一次调用）：文件 “/home/share_data1/tiancd/00.software/ERICA/vcf2MSA.py”，第 212 行，如果 GT[j] == '.'：索引错误：列出索引超出范围
> 
> 嗨，我在使用该软件时遇到以下错误，但无法解决，原因可能是什么？

hi, Has your problem been solved?

**Comment by tcd11221** [comment]
The problem has since been resolved, but the records were lost due to computer problems and I now forget how it was resolved at the time

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年10月5日 9:48
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [YuboZhangPKU/ERICA] IndexError: list index out of range (Issue #3)


python “/home/share_data1/tiancd/00.software/ERICA/vcf2MSA.py” -i new.test.vcf -r 1316.genome.fasta -o pop_test -f diplo -P1 pop1-108，pop1-xyy，pop1-bl，pop1-mgy -P2 pop2-107，pop2-17，pop2-203，pop2-214 -P3 pop3-69，pop3-1041，pop3-351，pop3-352 -P4 pop4-101，pop4-hy，pop4-xjy，pop4-1316 将分析四个人群。流行1 流行1-108 流行1 流行1-xyy 流行1 流行1-BL 流行1 流行1-MGY 流行2 流行2-107 流行2 流行2-17 流行2 流行2-203 流行2 流行2-214 流行3 流行3-69 流行3 流行3-1041 流行3 流行3-351 流行3-3 流行352 流行4-4 流行101 流行4-hy 流行4 流行4-xjy 流行4 流行4-4 周四 1316 月 29 日 23：12：55 2023 将分析染色体 Chr01。回溯（最近一次调用）：文件 “/home/share_data1/tiancd/00.software/ERICA/vcf2MSA.py”，第 212 行，如果 GT[j] == '.'：索引错误：列出索引超出范围

嗨，我在使用该软件时遇到以下错误，但无法解决，原因可能是什么？

hi, Has your problem been solved?

―
