### ISSUE TITLE
问题请教：

### ISSUE THREAD

**Issue by hfLi66** [YuboZhangPKU/ERICA#5]
> > 您好，当前的报错可能是由于依赖的模块版本问题或模块间存在冲突，请先尝试一下测试数据能否正常运行。如果仍存在报错，可能需要重新安装。对于预训练的模型，请尝试使用绝对路径指定其位置。

非常感谢您的指导，我们将新建的2个ERICA环境及工具删除后，重新安装后，没有再出现此类报错。
但又生成新的报错，我们怀疑是上步生成的msa文件有误，所以重新生成了一遍msa文件，但依旧是同样的报错，报错内容如下： 
WARNING:tensorflow:From /data/home/lihuifang/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From ERICAPrediction.py:291: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From /data/home/lihuifang/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
------------------------------
2023-10-09 00:40:18.781153: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2023-10-09 00:40:18.829204: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2023-10-09 00:40:18.836863: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5566b5071950 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-10-09 00:40:18.836923: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-10-09 00:40:18.837239: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Mon Oct  9 00:40:19 2023        result56/five_pop_ind_Chr1.txt  Data Preprocessing > > > > > > > > > >

Process Process-1:
Traceback (most recent call last):
  File "/data/home/lihuifang/miniconda3/envs/ERICA/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/home/lihuifang/miniconda3/envs/ERICA/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "ERICAPrediction.py", line 129, in FiveTaxonDataPrediction
    data = FiveTaxonDataProcess(MSA)
  File "ERICAPrediction.py", line 93, in FiveTaxonDataProcess
    lines = np.array([list(x) for x in lines], dtype=np.uint8)
ValueError: invalid literal for int() with base 10: '*'

想请教张老师，请问上面这个报错是什么原因造成的？我们该如何解决？
谢谢！

_Originally posted by @echolihuifang in https://github.com/YuboZhangPKU/ERICA/issues/4#issuecomment-1752105074_

**Comment by YuboZhangPKU** [comment]
您好，ERICAPrediction命令处理序列比对文件时支持的字符包括A,T,C,G,N（大写或小写）和-，请您检查一下输入文件中是否存在其他字符，如存在可能需要将其去除。

**Comment by hfLi66** [comment]
张老师您好，非常感谢您的指导，我们已经顺利跑通ERICA的所有流程。先前一直报错的原因是我们前期的vcf文件过滤条件不当，现已解决。
ERICA真是一个非常优美的工作，再次感谢您的耐心指导，祝好~
