### ISSUE TITLE
示例数据运行错误

### ISSUE THREAD

**Issue by zrr97** [YuboZhangPKU/ERICA#6]
张老师好，我安装软件的时候没有提示报错，用conda安装依赖环境的时候也没有提示报错。
git clone https://github.com/YuboZhangPKU/ERICA.git
cd ERICA
conda create --name ERICA python=3.6 tensorflow=2.1.0 plotnine=0.6.0

但是运行示例数据的时候，有报错。以下是运行命令是报错情况。

(ERICA) (ERICA)[zhurr@shilab ERICA]$ ./test.sh
-bash: ./test.sh: Permission denied
(ERICA) (ERICA)[zhurr@shilab ERICA]$ sh ./test.sh
Four populations will be analysed.
pop1    H_m_aglaope_1
pop1    H_m_aglaope_2
pop1    H_m_aglaope_3
pop1    H_m_aglaope_4
pop2    H_m_amaryllis_1
pop2    H_m_amaryllis_2
pop2    H_m_amaryllis_3
pop2    H_m_amaryllis_4
pop3    H_t_thelxinoe_1
pop3    H_t_thelxinoe_2
pop3    H_t_thelxinoe_3
pop3    H_t_thelxinoe_4
pop4    H_ethilla_1
pop4    H_ethilla_2
pop4    H_ethilla_3
pop4    H_ethilla_4
Tue May 21 14:27:20 2024        Chromosome Hmel218003o will be analysed.
Tue May 21 14:27:23 2024        Chromosome Hmel218003o done.
Traceback (most recent call last):
  File "ERICAPrediction.py", line 22, in <module>
    import tensorflow as tf
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 947, in _find_and_load_unlocked
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 75, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 25, in <module>
    from absl import logging
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/absl/logging/__init__.py", line 97, in <module>
    from absl import flags
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "ERICAVisualization.py", line 60, in <module>
    with open (ARGS.InputFile,'r') as filein:
FileNotFoundError: [Errno 2] No such file or directory: 'test/pop_test_Hmel218003o_res.txt'
Five populations will be analysed.
pop1    GP39
pop1    GP77
pop1    GP536
pop1    GP640
pop1    GP761-1
pop1    GP536
pop1    GP536
pop1    GP536
pop2    Nipponbare
pop2    HP14
pop2    HP44
pop2    HP48
pop2    HP314
pop2    HP103
pop2    HP45
pop2    UR28
pop3    W1943
pop3    W3095-2
pop3    Orufi
pop3    W3078-2
pop3    W1943
pop3    W3095-2
pop3    Orufi
pop3    W3078-2
pop4    W0170
pop4    W1698
pop4    W1754
pop4    W0123-1
pop4    Oniva
pop4    Oniva
pop4    Oniva
pop4    Oniva
pop5    Obart
pop5    Obart
pop5    Obart
pop5    Obart
pop5    Obart
pop5    Obart
pop5    Obart
pop5    Obart
Tue May 21 14:27:25 2024        Chromosome 10 will be analysed.
Tue May 21 14:27:29 2024        Chromosome 10 done.
Traceback (most recent call last):
  File "ERICAPrediction.py", line 22, in <module>
    import tensorflow as tf
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 947, in _find_and_load_unlocked
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 75, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 25, in <module>
    from absl import logging
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/absl/logging/__init__.py", line 97, in <module>
    from absl import flags
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/public1/user/zhurr/miniconda3/envs/ERICA/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "ERICAVisualization.py", line 60, in <module>
    with open (ARGS.InputFile,'r') as filein:
FileNotFoundError: [Errno 2] No such file or directory: 'test/five_pop_test_10_res.txt'

**Comment by YuboZhangPKU** [comment]
您好，感谢您使用我们的软件。报错信息反映了tensorflow安装过程存在错误，可能与软件版本不兼容有关，可以考虑更改absl版本。类似的报错信息供参考。https://github.com/abseil/abseil-py/issues/277

**Comment by zrr97** [comment]
好的，我试一下，感谢！
