### ISSUE TITLE
训练数据

### ISSUE THREAD

**Issue by pengyan19** [YuboZhangPKU/ERICA#7]
你好，我想问一下假如想用自己的数据训练模型，里面的-l参数的数据是怎么制作的呢？

**Comment by YuboZhangPKU** [comment]
您好，感谢您的使用。Label文件是模型训练的目标，反映类群之间的演化关系。在当前的训练过程中，研究使用了ms等模拟软件产生数据集，模拟结果中包括序列以及与序列对应的谱系树。为了对谱系树进行编码，使用拓扑加权方法（可参考Twisst软件）计算了每种可能拓扑的相对比例，并以此作为神经网络训练的标签。具体数据产生过程可参考ScriptsForModelEvaluation/0DataSimulation.sh脚本。

**Comment by pengyan19** [comment]
你好，我今天用这个软件画图的时候，出现版本的问题，请问这个怎么解决？
Traceback (most recent call last):
  File "ERICAVisualization.py", line 21, in <module>
    from plotnine import *
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/__init__.py", line 1, in <module>
    from .qplot import qplot            # noqa: F401
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/qplot.py", line 9, in <module>
    from .ggplot import ggplot
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/ggplot.py", line 18, in <module>
    from .facets import facet_null
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/facets/__init__.py", line 1, in <module>
    from .facet_grid import facet_grid
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/facets/facet_grid.py", line 6, in <module>
    from .facet import facet, layout_null, combine_vars, add_missing_facets
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/facets/facet.py", line 11, in <module>
    from ..scales.scales import Scales
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/scales/__init__.py", line 83, in <module>
    from .limits import xlim, ylim, lims, expand_limits
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/scales/limits.py", line 8, in <module>
    from ..geoms import geom_blank
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/geoms/__init__.py", line 24, in <module>
    from .geom_label import geom_label
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/geoms/geom_label.py", line 4, in <module>
    from .geom_text import geom_text
  File "/public/home/pengyan/anaconda3/envs/ERICA/lib/python3.6/site-packages/plotnine/geoms/geom_text.py", line 6, in <module>
    from adjustText import adjust_text
  File "/public/home/pengyan/.local/lib/python3.6/site-packages/adjustText/__init__.py", line 1
    from __future__ import division, annotations
    ^
SyntaxError: future feature annotations is not defined

**Comment by YuboZhangPKU** [comment]
您好，这个报错可能是由于安装的adjustText包与python 3.6环境不兼容造成的。脚本中未调用adjustText包，因此应该可以不安装该包，或者安装改包适配python 3.6环境的版本。

**Comment by pengyan19** [comment]
嗯嗯，好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月16日(周日) 下午4:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YuboZhangPKU/ERICA] 训练数据 (Issue #7)




 
您好，这个报错可能是由于安装的adjustText包与python 3.6环境不兼容造成的。脚本中未调用adjustText包，因此应该可以不安装该包，或者安装改包适配python 3.6环境的版本。
